# Generated by Django 2.0 on 2018-01-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('no_choice', 'Не указан'), ('switch', 'Коммутатор'), ('logdog', 'LogDog'), ('statistic', 'Статистика'), ('gateway', 'Шлюз')], default='no_choice', max_length=15),
        ),
    ]
