# Generated by Django 2.0 on 2018-01-26 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0003_auto_20180113_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_activity',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 27, 0, 50, 5, 105553)),
        ),
    ]
