# Generated by Django 2.0 on 2018-02-04 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0004_device_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_packets', models.IntegerField()),
                ('rec_packets', models.IntegerField()),
                ('loss_packets', models.IntegerField()),
                ('mit_time', models.FloatField()),
                ('avg_time', models.FloatField()),
                ('max_time', models.FloatField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='device_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring_app.Device'),
        ),
    ]
