# Generated by Django 2.0 on 2018-02-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0005_auto_20180204_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='device_ip',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='mit_time',
            new_name='min_time',
        ),
    ]
