# Generated by Django 2.0 on 2018-02-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0007_auto_20180204_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='avg_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='loss_packets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='max_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='min_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='rec_packets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='send_packets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
