# Generated by Django 2.0 on 2018-02-28 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0011_remove_device_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network_point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_from', models.IntegerField(null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='connected_from',
        ),
        migrations.AddField(
            model_name='address',
            name='network_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monitoring_app.Network_point'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='network_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring_app.Network_point'),
        ),
    ]
