# Generated by Django 2.0 on 2018-03-01 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0012_auto_20180228_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='network_point',
        ),
    ]
