# Generated by Django 2.0 on 2018-03-01 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0013_remove_device_network_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='network_point',
        ),
    ]
