# Generated by Django 2.0 on 2018-03-01 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0014_remove_address_network_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='network_point',
            name='address',
            field=models.ForeignKey(default=3870, on_delete=django.db.models.deletion.CASCADE, to='monitoring_app.Address'),
            preserve_default=False,
        ),
    ]
