# Generated by Django 2.0 on 2018-03-01 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0015_network_point_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='network_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring_app.Network_point'),
        ),
    ]
