# Generated by Django 2.0 on 2018-03-05 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0018_auto_20180301_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network_point',
            old_name='lon',
            new_name='lng',
        ),
    ]
