# Generated by Django 2.0 on 2018-03-05 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0019_auto_20180305_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network_point',
            name='device',
        ),
        migrations.AddField(
            model_name='device',
            name='network_point',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring_app.Network_point'),
        ),
    ]
