# Generated by Django 2.0 on 2018-03-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0020_auto_20180305_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network_point',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='network_point',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
