# Generated by Django 2.0 on 2018-03-06 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0022_auto_20180306_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='network_point',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring_app.Network_point'),
        ),
    ]
