# Generated by Django 2.0 on 2018-03-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0024_auto_20180307_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='network_point',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
