# Generated by Django 2.0 on 2018-03-08 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0026_auto_20180308_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network_point',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='network_point',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True),
        ),
    ]
