# Generated by Django 2.0 on 2018-03-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0029_auto_20180308_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('no_choice', 'Не указан'), ('switch', 'Коммутатор'), ('logdog', 'LogDog'), ('ups', 'UPS'), ('gateway', 'Шлюз'), ('other', 'Другое')], default='no_choice', max_length=15),
        ),
        migrations.AlterField(
            model_name='device',
            name='host_ip',
            field=models.GenericIPAddressField(blank=True, default=None, null=True, protocol='IPv4', unique=True),
        ),
    ]
