# Generated by Django 2.0 on 2018-03-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0030_auto_20180310_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='host_ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
    ]
