# Generated by Django 2.0 on 2018-03-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0031_auto_20180310_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='host_ip',
            field=models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True, protocol='IPv4'),
        ),
    ]
