# Generated by Django 2.0 on 2018-03-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0033_auto_20180310_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='host_ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', unique=True),
        ),
    ]
