# Generated by Django 2.0 on 2018-03-11 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0034_auto_20180310_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
    ]
