# Generated by Django 2.0 on 2018-03-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0036_unmanaged_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unmanaged_device',
            name='network_points',
            field=models.ManyToManyField(blank=True, null=True, to='monitoring_app.Network_point'),
        ),
    ]
