# Generated by Django 2.0 on 2018-04-02 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0039_testclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestClass',
        ),
    ]
